### ISSUE TITLE
Error in example `printk_handler`

### ISSUE THREAD

**Issue by stevielavern** [synacktiv/bip#16]
Hello,

On IDA 7.5 with python3 `visit_call_printk` is failing to setup comments with error `TypeError: in method 'cfuncptr_t_set_user_cmt', argument 3 of type 'char const *'`.

This is due to `BipData.get_cstring(ea + 2)` returning `bytes` instead of `str`.
Replacing `s = BipData.get_cstring(ea + 2)` with `s = str(BipData.get_cstring(ea + 2))` fixes this issue.

Thanks for this project that will save me (and surely others) a lot of time. :)

**Comment by BrunoPujos** [comment]
Hello,

Thank you for reporting this problem. I fixed it in the develop branch so it will be merge at one time in the master branch.

I'm glad you like it, that was the goal :)

I am closing the issue but do not hesitate to re-open if needed or to open new ones.
