### ISSUE TITLE
Retrieving function's return type

### ISSUE THREAD

**Issue by assafcarlsbad** [synacktiv/bip#20]
Hi,

Is there any way I can get the deduced return type of a decompiled function object (`HxCFunc`)?
The only solution I came up with so far was stripping the first word from the function's text (i.e. `f.cstr.split()[0]`), but there's probably a better way to do so.
Did I miss anything?

Thanks in advance 🙏

**Comment by BrunoPujos** [comment]
Hello,

So there is currently no way to get the return type directly of a function. You have to go through the type of the function (`BTypeFunc` accessible through `BipFunction().type`) and then access its return type (`BipFunction().type.return_type` or `BipFunction().type.return_type.str` if you want the string). This should work (I hope) in both cases where you have typed your function or when it is deduced by IDA. If you are at the HexRays level you will want to fetch back the `BipFunction` (through the `bfunc` property for example).

A few notes about this: I agree that getting directly the return type of a function should be made more accessible from directly the function object. The reason I did not do this yet is that there is actually a confusion in Bip (my fault) between the type from the HexRays decompiler and the one returned by the basic IDA disassembler. The `type` property of the `BipFunction` object should actually be for the `HxCFunc` object. I intend to fix that (and a few other things) for the next stable release of Bip which I intend to be at the end of this month.

I hope this answers the question, I am closing the issue but do not hesitate to reopen if needed. I will also send you a message on this issue for keeping you updated of the change when the next stable release is actually done.
